//! Composed SQL: byte identity with the pre-carve constants, placeholder
//! shapes and column coverage.

use super::*;

fn sql_test_ts() -> DateTime<Utc> {
    Utc.timestamp_opt(1_752_000_000, 0).unwrap()
}

/// Minimal rows for the SQL-shape tests. Only the *shape* of the generated
/// statement is under test, so the values are arbitrary.
fn test_interaction(id: NodeId) -> Interaction {
    Interaction {
        id,
        session_id: SessionId::from("sql-shape"),
        agent_id: crate::types::AgentId::from("agent-a"),
        prompt_text: Some("p".into()),
        previous_id: None,
        created_at: sql_test_ts(),
        event_time: None,
    }
}

fn test_concept(origin: NodeId, content: &str) -> Concept {
    Concept {
        id: NodeId::new(),
        session_id: SessionId::from("sql-shape"),
        content: content.into(),
        canonical_key: content.into(),
        concept_type: ConceptType::Entity,
        origin_interaction: origin,
        origin_agent: crate::types::AgentId::from("agent-a"),
        created_at: sql_test_ts(),
        access_count: 0,
        last_accessed: None,
        gc_survived: 0,
        canonization_status: CanonizationStatus::None,
        blast_radius: None,
        last_demotion_time: None,
        embedding: None,
        human_confirmed: 0,
        embedding_source: None,
        chunk_group_id: None,
    }
}

fn test_edge(source: NodeId, target: NodeId, edge_type: EdgeType) -> Edge {
    Edge {
        id: NodeId::new(),
        session_id: SessionId::from("sql-shape"),
        source,
        target,
        edge_type,
        weight: 0.5,
        reinforcements: 1,
        created_at: sql_test_ts(),
        last_reinforced: sql_test_ts(),
        event_time: None,
    }
}

/// Count `$n` placeholders in a statement and return the max `n` (1-based).
fn placeholder_max(sql: &str) -> usize {
    let mut max = 0;
    let bytes = sql.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        if bytes[i] == b'$' && bytes[i + 1].is_ascii_digit() {
            let mut n = 0usize;
            let mut j = i + 1;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                n = n * 10 + (bytes[j] - b'0') as usize;
                j += 1;
            }
            max = max.max(n);
            i = j;
        } else {
            i += 1;
        }
    }
    max
}

/// Build the concept upsert for `n` rows and hand back its SQL text.
fn concept_sql_for(n: usize) -> String {
    let iid = NodeId::new();
    let concepts: Vec<Concept> = (0..n)
        .map(|k| {
            let mut c = test_concept(iid, &format!("c{k}"));
            c.embedding = Some(vec![0.5; 4]);
            c
        })
        .collect();
    let rows: Vec<ConceptRow<'_>> = concepts.iter().map(ConceptRow::new).collect();
    let embeddings: Vec<Option<String>> = vec![Some("[0.5,0.5,0.5,0.5]".into()); n];
    concept_upsert_query(&rows, &embeddings, CockroachDialect::VECTOR_CAST)
        .sql()
        .to_string()
}

/// B0-R1-1. Standing pin: every composed statement, the vector-cast token,
/// and `keyword_candidates_sql` for n = 1..5 are byte-identical to the
/// pre-carve constants in commit `7937de7`. The `PRE_*` bodies were
/// generated by a parser over `git show 7937de7:src/store/cockroach.rs`,
/// not transcribed by hand. A single whitespace change in any composed
/// statement, or a change to `STRING_CAST`, `VECTOR_CAST`, or
/// `DISTANCE_OP`, must fail here.
///
/// Deliberate exception (issue #2, re-pinned by hand): the two vector
/// candidate SELECTs now also fetch `canonical_key`, so the Rust side can
/// order exact score ties stably across runs. Their `PRE_*` bodies carry
/// that one added column; everything else stays parser-faithful.
///
/// Second deliberate exception (#22 PR 2, re-pinned by hand): the concept
/// SELECT also reads `embedding_source`, on its own line after
/// `human_confirmed`.
#[test]
fn b0_composed_sql_is_byte_identical_to_the_pre_carve_constants() {
    const PRE_VECTOR_CANDIDATES_SQL: &str = r#"
SELECT id::STRING AS id, session_id::STRING AS session_id,
       canonical_key::STRING AS canonical_key,
       embedding <-> $1::VECTOR AS dist
FROM concepts
WHERE embedding IS NOT NULL
ORDER BY dist ASC
LIMIT $2
"#;

    const PRE_SESSION_VECTOR_CANDIDATES_SQL: &str = r#"
SELECT id::STRING AS id, canonical_key::STRING AS canonical_key,
       embedding <-> $1::VECTOR AS dist
FROM concepts
WHERE session_id = $2 AND embedding IS NOT NULL
ORDER BY dist ASC, id ASC
LIMIT $3
"#;

    const PRE_UPSERT_SESSION_SQL: &str = r#"
INSERT INTO sessions (
    session_id, root_goal, created_at, closed_at,
    embedding_kind, embedding_model, embedding_dim, mutation_epoch,
    last_gc_epoch, last_gc_at
) VALUES ($1, $2::JSONB, COALESCE($3, now()), $4, $5::STRING, $6::STRING, $7::INT, $8::INT, $9::BIGINT, $10)
ON CONFLICT (session_id) DO UPDATE SET
    root_goal = EXCLUDED.root_goal,
    created_at = EXCLUDED.created_at,
    closed_at = EXCLUDED.closed_at,
    embedding_kind = EXCLUDED.embedding_kind,
    embedding_model = EXCLUDED.embedding_model,
    embedding_dim = EXCLUDED.embedding_dim,
    mutation_epoch = EXCLUDED.mutation_epoch,
    last_gc_epoch = EXCLUDED.last_gc_epoch,
    last_gc_at = EXCLUDED.last_gc_at
"#;

    const PRE_SET_EMBEDDING_SQL: &str = r#"
UPDATE sessions
SET embedding_kind = $2::STRING,
    embedding_model = $3::STRING,
    embedding_dim = $4::INT
WHERE session_id = $1
"#;

    const PRE_SELECT_SESSION_SQL: &str = r#"
SELECT root_goal::STRING AS root_goal, created_at, closed_at,
       embedding_kind, embedding_model, embedding_dim, mutation_epoch,
       last_gc_epoch, last_gc_at
FROM sessions
WHERE session_id = $1
"#;

    const PRE_SELECT_INTERACTIONS_SQL: &str = r#"
SELECT id::STRING AS id, session_id, agent_id, prompt_text,
       previous_id::STRING AS previous_id, created_at, event_time
FROM interactions
WHERE session_id = $1
ORDER BY created_at, id
"#;

    const PRE_SELECT_CONCEPTS_SQL: &str = r#"
SELECT id::STRING AS id, session_id, content, canonical_key, concept_type,
       origin_interaction::STRING AS origin_interaction, origin_agent, created_at,
       access_count, last_accessed, gc_survived, canonization_status, blast_radius,
       last_demotion_time, embedding::STRING AS embedding, chunk_group_id, human_confirmed,
       embedding_source
FROM concepts
WHERE session_id = $1
ORDER BY id
"#;

    const PRE_SELECT_EDGES_SQL: &str = r#"
SELECT id::STRING AS id, session_id, source::STRING AS source,
       target::STRING AS target, edge_type, weight, reinforcements,
       created_at, last_reinforced, event_time
FROM edges
WHERE session_id = $1
ORDER BY id
"#;

    const PRE_SELECT_CANONIZATION_EVENTS_SQL: &str = r#"
SELECT id::STRING AS id, session_id, node_id::STRING AS node_id,
       from_status, to_status, blast_radius, last_demotion_time, occurred_at
FROM canonization_events
WHERE session_id = $1
ORDER BY occurred_at, id
"#;

    const PRE_SELECT_RESERVATIONS_SQL: &str = r#"
SELECT session_id, node_id::STRING AS node_id, agent_id, expires_at
FROM reservations
WHERE session_id = $1
"#;

    let sql = crdb_sql();
    assert_eq!(
        sql.vector_candidates, PRE_VECTOR_CANDIDATES_SQL,
        "vector_candidates"
    );
    assert_eq!(
        sql.session_vector_candidates, PRE_SESSION_VECTOR_CANDIDATES_SQL,
        "session_vector_candidates"
    );
    assert_eq!(sql.upsert_session, PRE_UPSERT_SESSION_SQL, "upsert_session");
    assert_eq!(sql.set_embedding, PRE_SET_EMBEDDING_SQL, "set_embedding");
    assert_eq!(sql.select_session, PRE_SELECT_SESSION_SQL, "select_session");
    assert_eq!(
        sql.select_interactions, PRE_SELECT_INTERACTIONS_SQL,
        "select_interactions"
    );
    assert_eq!(
        sql.select_concepts, PRE_SELECT_CONCEPTS_SQL,
        "select_concepts"
    );
    assert_eq!(sql.select_edges, PRE_SELECT_EDGES_SQL, "select_edges");
    assert_eq!(
        sql.select_canonization_events, PRE_SELECT_CANONIZATION_EVENTS_SQL,
        "select_canonization_events"
    );
    assert_eq!(
        sql.select_reservations, PRE_SELECT_RESERVATIONS_SQL,
        "select_reservations"
    );
    assert_eq!(sql.vector_cast, "::VECTOR", "vector_cast");

    // Pre-carve `keyword_candidates_sql` builder, copied from 7937de7
    // (the `::STRING` prefix was a literal then; it is now `STRING_CAST`).
    fn pre_keyword_candidates_sql(n_tokens: usize) -> String {
        debug_assert!(n_tokens > 0);
        let mut sql = String::with_capacity(64 + n_tokens * 96);
        sql.push_str(
            "SELECT id::STRING AS id, content, canonical_key FROM concepts WHERE session_id = $1 AND (",
        );
        for i in 0..n_tokens {
            if i > 0 {
                sql.push_str(" OR ");
            }
            let n = i + 2;
            sql.push_str(&format!(
                "strpos(lower(content), ${n}) > 0 OR strpos(lower(canonical_key), ${n}) > 0"
            ));
        }
        sql.push(')');
        sql
    }
    for n in 1..=5 {
        assert_eq!(
            keyword_candidates_sql::<CockroachDialect>(n),
            pre_keyword_candidates_sql(n),
            "keyword_candidates_sql n={n}"
        );
    }
}

#[test]
fn upsert_placeholder_shapes_match_structs() {
    // Snapshot->row mapping shapes: every struct column has exactly one placeholder
    // and the column counts match the INSERT column lists. Upserts are built
    // per-call by `QueryBuilder` now (L82-1), so a single row is the shape
    // the old fixed-placeholder statements had.
    let iid = NodeId::new();
    let i = test_interaction(iid);
    // Asserted against the shared column constants, not bare literals: those
    // constants are what the per-adapter bind-parameter const-asserts divide
    // the backend limit by (R1-4), so a column added to a statement without
    // updating them must fail here rather than silently widen a chunk past
    // the limit.
    assert_eq!(
        placeholder_max(interaction_upsert_query(&[&i]).sql()),
        INTERACTION_COLUMNS
    );
    assert_eq!(placeholder_max(&concept_sql_for(1)), CONCEPT_COLUMNS);
    let e = test_edge(iid, iid, EdgeType::Derives);
    assert_eq!(
        placeholder_max(edge_upsert_query(&[&e]).sql()),
        EDGE_COLUMNS
    );
    // STORE-1: the full-snapshot upsert now carries the embedding contract
    // (kind/model/dim) alongside root_goal/created_at/closed_at.
    // Issue #17 added mutation_epoch ($8) without updating this count, so
    // the assertion was red on this (CI-disabled) row from 5709a72 on;
    // issue #29 adds last_gc_epoch ($9) and last_gc_at ($10).
    let upsert_session = crdb_sql().upsert_session;
    assert_eq!(placeholder_max(&upsert_session), 10);
    assert!(upsert_session.contains("mutation_epoch = EXCLUDED.mutation_epoch"));
    assert!(upsert_session.contains("last_gc_epoch = EXCLUDED.last_gc_epoch"));
    assert!(upsert_session.contains("last_gc_at = EXCLUDED.last_gc_at"));
    assert!(upsert_session.contains("embedding_kind = EXCLUDED.embedding_kind"));
    assert!(upsert_session.contains("embedding_dim = EXCLUDED.embedding_dim"));
    // Issue #29: the per-flush session-row stamp (shared by both pg
    // dialects) carries the re-anchor flag as $5 and keeps the epoch merge
    // a plain GREATEST.
    let stamp = crate::store::pg::UPSERT_SESSION_ROW_SQL;
    assert_eq!(placeholder_max(stamp), 5);
    assert!(
        stamp.contains("CASE WHEN $5::BOOL AND EXCLUDED.last_gc_epoch >= sessions.last_gc_epoch")
    );
    assert!(
        stamp.contains("last_gc_epoch = GREATEST(sessions.last_gc_epoch, EXCLUDED.last_gc_epoch)")
    );
    assert_eq!(placeholder_max(INSERT_CANONIZATION_EVENT_SQL), 8);
    assert_eq!(placeholder_max(UPDATE_CONCEPT_STATUS_SQL), 5);
    assert_eq!(placeholder_max(UPSERT_SYNONYM_SQL), 3);
    assert_eq!(placeholder_max(UPSERT_RESERVATION_SQL), 4);
    // COH-3: the canonization surface carries last_demotion_time end to end.
    assert!(UPDATE_CONCEPT_STATUS_SQL.contains("COALESCE($5, last_demotion_time)"));
    assert!(INSERT_CANONIZATION_EVENT_SQL.contains("last_demotion_time"));
    // The vector column carries the ::VECTOR cast; chunk_group_id (T2.5) is
    // the 16th, nullable; human_confirmed (C2) is the 17th; embedding_source
    // (#22) closes the list as the 18th — all included in the conflict UPDATE.
    let concept_sql = concept_sql_for(1);
    assert!(concept_sql.contains("$15::VECTOR"), "{concept_sql}");
    assert!(concept_sql.contains("embedding = EXCLUDED.embedding"));
    assert!(concept_sql.contains("chunk_group_id = EXCLUDED.chunk_group_id"));
    assert!(
        concept_sql.contains("human_confirmed"),
        "the C2 count rides the upsert: {concept_sql}"
    );
    assert!(
        concept_sql.contains("embedding_source = EXCLUDED.embedding_source"),
        "the #22 provenance rides the upsert: {concept_sql}"
    );
    // Edge conflict targets the natural key; id is replaceable on conflict.
    assert!(edge_upsert_query(&[&e])
        .sql()
        .contains("ON CONFLICT (source, target, edge_type)"));
}

/// Issue #30: the shared narrow access update binds `ACCESS_COLUMNS` per
/// row and carries no `::VECTOR` (or any) cast — the same text as on
/// PostgreSQL, so CockroachDB never rewrites the embedding for a read.
#[test]
fn the_access_update_is_shared_and_cast_free() {
    let sid = crate::types::SessionId::from("issue-30");
    let rows = [crate::store::batch::AccessUpdate {
        session_id: &sid,
        id: NodeId::new(),
        access_count: 1,
        last_accessed: chrono::Utc::now(),
    }];
    let access_sql = access_update_query(&rows).sql().to_string();
    assert_eq!(placeholder_max(&access_sql), ACCESS_COLUMNS);
    assert!(!access_sql.contains("::"), "{access_sql}");
    assert!(access_sql.contains("GREATEST(concepts.access_count, v.access_count)"));
}

/// **L82-1.** The flush issues one *multi-row* statement per planned chunk,
/// and the generated SQL is the half of that change no test on this machine
/// can put in front of a cluster — so it is asserted directly.
///
/// Three rows must produce 54 placeholders (3 x `CONCEPT_COLUMNS`) in three
/// `VALUES` tuples, carry the `::VECTOR` cast on *each* row's embedding
/// placeholder (the cast is part of the value expression, not the
/// statement), and end in exactly one `ON CONFLICT` clause.
#[test]
fn sql_shape_is_a_multi_row_upsert() {
    let sql = concept_sql_for(3);
    assert_eq!(
        placeholder_max(&sql),
        54,
        "3 rows x 18 columns, numbered across the whole statement: {sql}"
    );
    for n in [15, 33, 51] {
        assert!(
            sql.contains(&format!("${n}::VECTOR")),
            "every row's embedding placeholder needs its own cast, missing ${n}: {sql}"
        );
    }
    assert_eq!(
        sql.matches("ON CONFLICT").count(),
        1,
        "the conflict clause is appended once, after the whole VALUES list: {sql}"
    );
    assert_eq!(
        sql.matches("INSERT INTO concepts").count(),
        1,
        "one statement, not three: {sql}"
    );

    // Edges keep the natural-key conflict target across rows.
    let a = NodeId::new();
    let edges = [
        test_edge(a, NodeId::new(), EdgeType::Causal),
        test_edge(a, NodeId::new(), EdgeType::Dependency),
    ];
    let refs: Vec<&Edge> = edges.iter().collect();
    let edge_sql = edge_upsert_query(&refs).sql().to_string();
    assert_eq!(placeholder_max(&edge_sql), 20, "2 rows x 10 columns");
    assert_eq!(edge_sql.matches("ON CONFLICT").count(), 1);
}

/// D-R1-2 (no live cluster: SQL text is the contract). A **non-NULL**
/// event_time must survive the whole statement path: bound as the LAST
/// column of both multi-row upserts (matching the column list, so a bind
/// that drifted onto `created_at`'s slot changes the placeholder count),
/// carried by `DO UPDATE SET` so the natural-key replace cannot erase it,
/// and read back by name in both SELECTs. The sqlite adapter reads this
/// column positionally — this is where a column-order regression shows.
#[test]
fn event_time_rides_the_upsert_and_select_shape() {
    let stamped_at = Utc.timestamp_opt(946_684_799, 0).unwrap();

    let mut i = test_interaction(NodeId::new());
    i.event_time = Some(stamped_at);
    let i_sql = interaction_upsert_query(&[&i]).sql().to_string();
    assert_eq!(placeholder_max(&i_sql), 7, "1 row x 7 columns: {i_sql}");
    assert!(
        i_sql.contains("previous_id, created_at, event_time"),
        "event_time closes the INSERT column list: {i_sql}"
    );

    let mut e = test_edge(NodeId::new(), NodeId::new(), EdgeType::Causal);
    e.event_time = Some(stamped_at);
    let e_sql = edge_upsert_query(&[&e]).sql().to_string();
    assert_eq!(placeholder_max(&e_sql), 10, "1 row x 10 columns: {e_sql}");
    assert!(
        e_sql.contains("last_reinforced, event_time"),
        "event_time closes the INSERT column list: {e_sql}"
    );

    // Whole-record replace on conflict is only consistent while BOTH
    // halves carry the stamp (I2 convention).
    for sql in [&i_sql, &e_sql] {
        let (_, on_conflict) = sql
            .split_once("ON CONFLICT")
            .expect("the upsert has a conflict clause");
        assert!(
            on_conflict.contains("event_time = EXCLUDED.event_time"),
            "conflict update must re-stamp from the incoming row: {sql}"
        );
    }

    let crdb = crdb_sql();
    for sql in [&crdb.select_interactions, &crdb.select_edges] {
        assert!(
            sql.contains("event_time"),
            "load must read event_time back by name: {sql}"
        );
    }
}

/// C2 (no live cluster: SQL text is the contract). `human_confirmed` —
/// the solo score's persisted input — must ride the whole statement path:
/// bound as the 17th concept column, right after `chunk_group_id` (a bind
/// drifting onto another slot changes the placeholder count), carried by
/// `DO UPDATE SET` so a whole-record replace cannot reset a confirmed
/// concept to never-confirmed, and read back by name in the SELECT. The
/// sqlite adapter reads this column positionally (`try_get(16)`) — that is
/// where an order regression shows.
#[test]
fn human_confirmed_rides_the_concept_upsert_and_select_shape() {
    let mut c = test_concept(NodeId::new(), "load-bearing warning");
    c.human_confirmed = 7;
    let sql = concept_upsert_query(
        &[crate::store::batch::ConceptRow::new(&c)],
        &[None],
        CockroachDialect::VECTOR_CAST,
    )
    .sql()
    .to_string();
    assert_eq!(placeholder_max(&sql), 18, "1 row x 18 columns: {sql}");
    assert!(
        sql.contains("chunk_group_id, human_confirmed"),
        "human_confirmed follows chunk_group_id in the INSERT column list: {sql}"
    );
    let (_, on_conflict) = sql
        .split_once("ON CONFLICT")
        .expect("the upsert has a conflict clause");
    assert!(
        on_conflict.contains("human_confirmed = EXCLUDED.human_confirmed"),
        "conflict update must carry the count from the incoming row: {sql}"
    );
    assert!(
        crdb_sql().select_concepts.contains("human_confirmed"),
        "load must read human_confirmed back by name"
    );
}

/// #22 PR 2 (no live cluster: SQL text is the contract). A supplied
/// vector's provenance must ride the whole statement path on Cockroach:
/// bound as the LAST (18th) concept column, carried by `DO UPDATE SET`
/// with the vector it describes (so nulling an image vector also clears
/// its source), and read back by name. The sqlite adapter reads it
/// positionally (`try_get(17)`), so an order regression shows there.
#[test]
fn embedding_source_rides_the_concept_upsert_and_select_shape() {
    let mut c = test_concept(NodeId::new(), "outfit for onam [image:abc]");
    c.embedding_source = Some(crate::types::EmbeddingSource {
        modality: crate::types::SourceModality::Image,
        origin: crate::types::VectorOrigin::Client,
        sha256: None,
        mime: None,
    });
    let sql = concept_upsert_query(
        &[crate::store::batch::ConceptRow::new(&c)],
        &[None],
        CockroachDialect::VECTOR_CAST,
    )
    .sql()
    .to_string();
    assert_eq!(placeholder_max(&sql), CONCEPT_COLUMNS, "{sql}");
    assert!(
        sql.contains("human_confirmed, embedding_source\n)"),
        "embedding_source closes the INSERT column list: {sql}"
    );
    assert!(
        sql.contains(&format!("${CONCEPT_COLUMNS})")),
        "its value is the last bind of the row: {sql}"
    );
    let (_, on_conflict) = sql
        .split_once("ON CONFLICT")
        .expect("the upsert has a conflict clause");
    assert!(
        on_conflict.contains("embedding_source = EXCLUDED.embedding_source"),
        "conflict update must carry the provenance with the vector: {sql}"
    );
    assert!(
        crdb_sql().select_concepts.contains("embedding_source"),
        "load must read embedding_source back by name"
    );
}

/// R2-1 (no live cluster: SQL text is the contract). The three
/// canonization columns are INSERT-only — present in the column list so a
/// brand-new row carries them, absent from `DO UPDATE SET` so a stale
/// `Mutation::UpsertNode` snapshot cannot take an already-recorded hop
/// back out of the row (or erase a demotion cooldown). `gc_survived`,
/// which shares the same appenders, must still be updated: the property
/// is column ownership, not a blanket skip.
///
/// The multi-row rewrite (L82-1) is exactly where this could have been lost,
/// so the assertion runs against the generated statement rather than a
/// constant — and `store::batch` carries the matching property for the
/// *values*: a deduplicated row takes its canonization columns from the
/// first occurrence, which is what row-by-row replay left in the row.
#[test]
fn concept_upsert_does_not_write_the_canonization_columns_on_conflict() {
    let sql = concept_sql_for(2);
    let (insert, on_conflict) = sql
        .split_once("ON CONFLICT")
        .expect("the concept upsert has a conflict clause");
    for col in ["canonization_status", "blast_radius", "last_demotion_time"] {
        assert!(
            insert.contains(col),
            "{col} must stay in the INSERT column list (new rows carry it)"
        );
        assert!(
            !on_conflict.contains(col),
            "{col} is written only by the canonization path (R2-1)"
        );
    }
    assert!(
        sql.contains("gc_survived = EXCLUDED.gc_survived"),
        "the upsert's own columns must still update on conflict"
    );
    // The canonization path is that single writer.
    assert!(UPDATE_CONCEPT_STATUS_SQL.contains("canonization_status"));
    assert!(UPDATE_CONCEPT_STATUS_SQL.contains("blast_radius"));
    assert!(UPDATE_CONCEPT_STATUS_SQL.contains("last_demotion_time"));
}

#[test]
fn structural_query_placeholder_order_and_counts() {
    // §4.1 SQL construction: exactly three binds, in (session, node, cutoff) order.
    assert_eq!(placeholder_max(BLAST_RADIUS_SQL), 3);
    assert_eq!(placeholder_max(INTERACTION_SPAN_SQL), 3);
    for sql in [BLAST_RADIUS_SQL, INTERACTION_SPAN_SQL] {
        let p1 = sql.find("$1").unwrap();
        let p2 = sql.find("$2").unwrap();
        let p3 = sql.find("$3").unwrap();
        assert!(p1 < p2 && p2 < p3, "placeholders must appear in bind order");
    }
    // Errata: structural edge types only; provenance must not appear.
    for sql in [BLAST_RADIUS_SQL, INTERACTION_SPAN_SQL] {
        assert!(
            sql.contains("'Dependency', 'Causal', 'Hierarchical'"),
            "{sql}"
        );
        assert!(!sql.contains("Derives"), "{sql}");
        assert!(!sql.contains("Temporal"), "{sql}");
        // Concept-sourced only: source JOIN pins src to a concept row.
        assert!(sql.contains("JOIN concepts src"), "{sql}");
    }
    // MemoryStore parity: interaction_span filters BOTH edge and interaction
    // age — each resolved through D's fallback rule (COALESCE with event_time).
    assert!(INTERACTION_SPAN_SQL.contains("COALESCE(e.event_time, e.created_at) <= $3"));
    assert!(INTERACTION_SPAN_SQL.contains("COALESCE(i.event_time, i.created_at) <= $3"));
}

/// F5: `origin_interaction` is a global FK, so the span CTE must scope the
/// joined interaction to the queried session — the extent CTE already is.
/// Without it, concepts pointing at another session's interactions inflate
/// `distinct` and push the ratio above 1.0 (MemoryStore never sees them).
/// Text-level like its `structural_query_placeholder_order_and_counts`
/// neighbour: the behavioural twin runs on SQLite
/// (`interaction_span_ignores_cross_session_origin_interactions`), which
/// needs no live cluster.
#[test]
fn span_sql_is_session_scoped_and_coverage_is_clamped() {
    assert!(
        INTERACTION_SPAN_SQL.contains("i.session_id = $1"),
        "span CTE must scope the origin interaction to the session (F5)"
    );
    assert!(
        INTERACTION_SPAN_SQL.contains("least(1.0, greatest(0.0,"),
        "coverage must be clamped to [0,1] like MemoryStore/SQLite (F5)"
    );
}

#[test]
fn keyword_sql_placeholder_counts_and_order() {
    for n in [1usize, 2, 3, 7] {
        let sql = keyword_candidates_sql::<CockroachDialect>(n);
        // $1 (session) once; each of $2..$n+1 (token) exactly twice (content + key).
        assert_eq!(placeholder_max(&sql), n + 1);
        let mut counts = std::collections::HashMap::new();
        for m in sql.split('$').skip(1) {
            let digits: String = m.chars().take_while(|c| c.is_ascii_digit()).collect();
            if !digits.is_empty() {
                *counts
                    .entry(digits.parse::<usize>().unwrap())
                    .or_insert(0usize) += 1;
            }
        }
        assert_eq!(counts[&1], 1);
        for k in 2..=n + 1 {
            assert_eq!(
                counts[&k], 2,
                "token placeholder ${k} used for content and key"
            );
        }
    }
    // No LIKE wildcards: strpos(lower(...)) is exact substring (MemoryStore contains).
    let sql = keyword_candidates_sql::<CockroachDialect>(1);
    assert!(sql.contains("strpos(lower(content), $2) > 0"));
    assert!(!sql.contains("ILIKE") && !sql.contains("LIKE"), "{sql}");
}
