//! P2 exit-criteria integration test: rebuild `session-rest-api` **from
//! scratch** using only the public write APIs, then compare the result against
//! the committed fixture snapshot.
//!
//! Covered write path: `Graph::insert_interaction` (T2.1, temporal chain +
//! structural `Temporal` edges), `Graph::declare_synonym` (T2.1),
//! `derive()` (T2.3 — canonicalization via T2.2, fresh concepts, structural
//! `Derives` edges), `Graph::upsert_edge` (T2.1, the fixture's `Dependency`
//! edges), and `canonicalize()` (T2.2) end-to-end through the synonym table.
//!
//! What is deliberately NOT reproduced: daemon-earned state (`gc_survived`,
//! `CanonizationStatus`, `blast_radius`) — the write path yields fresh
//! concepts (`gc_survived = 0`, status `None`); the daemon and canonization
//! tracks (P4/P6) earn that state later. This is the write-path boundary.

#![cfg(feature = "fixtures")]

use lambo::graph::canonical::{canonicalize, CanonicalizeResult};
use lambo::graph::derive::{derive, ParentOf};
use lambo::graph::Graph;
use lambo::types::{CanonizationStatus, ConceptType, Edge as GraphEdge, EdgeType, Node, NodeId};
use std::collections::{BTreeSet, HashMap};

/// Label for structural comparison: concept content, else interaction prompt.
fn label_for(g: &Graph, id: NodeId) -> String {
    match g.node(id) {
        Some(Node::Concept(c)) => c.content.clone(),
        Some(Node::Interaction(i)) => i.prompt_text.clone().unwrap_or_default(),
        None => panic!("{id} missing from rebuilt graph"),
    }
}

/// The fixture's edge set as (source label, target label, type, weight-bits).
fn oracle_edge_set(
    edges: &[GraphEdge],
    label: &HashMap<NodeId, String>,
) -> BTreeSet<(String, String, String, u64)> {
    edges
        .iter()
        .map(|e| {
            (
                label[&e.source].clone(),
                label[&e.target].clone(),
                format!("{:?}", e.edge_type),
                e.weight.to_bits(),
            )
        })
        .collect()
}

#[test]
fn rebuilds_session_rest_api_via_public_write_apis() {
    let oracle = lambo::fixtures::load_snapshot("session-rest-api").unwrap();
    let sid = oracle.session_id.clone();

    let mut g = Graph::new(sid.clone());

    // 1. Interactions — fixture ids reused so `origin_interaction` references
    //    in step 3 resolve. insert_interaction builds the temporal chain and
    //    the 11 structural `Temporal` edges.
    for i in &oracle.interactions {
        g.insert_interaction(i.clone()).unwrap();
    }
    assert_eq!(g.temporal_chain().len(), oracle.interactions.len());

    // 2. Synonym state (exercised end-to-end in step 6).
    g.declare_synonym("register_user", "create_user");

    // 3. Concepts via derive() — ONE per call so no `CoOccurrence` edges
    //    appear (the fixture has none). Each call also creates the structural
    //    `Derives` edge from the origin interaction, exactly like the fixture.
    let mut by_content: HashMap<String, NodeId> = HashMap::new();
    for c in &oracle.concepts {
        let outcome = derive(
            &mut g,
            c.origin_interaction,
            &c.origin_agent,
            &[(c.content.as_str(), c.concept_type)],
            &ParentOf::none(),
            10,
        )
        .unwrap();
        assert_eq!(outcome.created.len(), 1, "create {:?}", c.content);
        assert!(outcome.matched.is_empty(), "fresh concept matched: {c:?}");
        let node = outcome.created[0];
        by_content.insert(c.content.clone(), node);

        let built = match g.node(node).unwrap() {
            Node::Concept(c) => c,
            _ => panic!("not a concept"),
        };
        // The canonicalization pipeline reproduced the fixture's key exactly.
        assert_eq!(
            built.canonical_key, c.canonical_key,
            "key of {:?}",
            c.content
        );
        assert_eq!(built.concept_type, c.concept_type);
        assert_eq!(built.origin_interaction, c.origin_interaction);
        assert_eq!(built.origin_agent, c.origin_agent);
    }
    assert_eq!(by_content.len(), oracle.concepts.len());

    // 4. Fixture `Dependency` edges via upsert_edge, endpoints remapped from
    //    fixture seed ids to the rebuilt (fresh-id) nodes.
    let oracle_content_by_id: HashMap<NodeId, String> = oracle
        .concepts
        .iter()
        .map(|c| (c.id, c.content.clone()))
        .collect();
    for e in &oracle.edges {
        if e.edge_type != EdgeType::Dependency {
            continue; // Temporal + Derives are generated by steps 1 and 3.
        }
        let edge = GraphEdge {
            id: e.id,
            session_id: sid.clone(),
            source: by_content[&oracle_content_by_id[&e.source]],
            target: by_content[&oracle_content_by_id[&e.target]],
            edge_type: EdgeType::Dependency,
            weight: e.weight,
            reinforcements: e.reinforcements,
            created_at: e.created_at,
            last_reinforced: e.last_reinforced,
        };
        g.upsert_edge(edge).unwrap();
    }

    // 5. Structural equality with the fixture: same node kinds/counts and the
    //    SAME edge multiset when labeled by content / prompt.
    g.assert_invariants().unwrap();
    assert_eq!(
        g.node_count(),
        oracle.interactions.len() + oracle.concepts.len()
    );
    assert_eq!(g.edge_count(), oracle.edges.len());

    let oracle_label: HashMap<NodeId, String> = oracle
        .interactions
        .iter()
        .map(|i| (i.id, i.prompt_text.clone().unwrap_or_default()))
        .chain(oracle.concepts.iter().map(|c| (c.id, c.content.clone())))
        .collect();
    let mut rebuild_label: HashMap<NodeId, String> = oracle
        .interactions
        .iter()
        .map(|i| (i.id, i.prompt_text.clone().unwrap_or_default()))
        .collect();
    for (content, id) in &by_content {
        rebuild_label.insert(*id, content.clone());
    }

    let rebuilt_edges: BTreeSet<(String, String, String, u64)> = g
        .snapshot()
        .edges
        .iter()
        .map(|e| {
            (
                label_for(&g, e.source),
                label_for(&g, e.target),
                format!("{:?}", e.edge_type),
                e.weight.to_bits(),
            )
        })
        .collect();
    assert_eq!(
        rebuilt_edges,
        oracle_edge_set(&oracle.edges, &oracle_label),
        "edge structure must match the fixture exactly"
    );

    // 6. Synonym pipeline end-to-end: the raw key resolves through the declared
    //    synonym to the create-user concept; the un-synonymed form stays apart.
    match canonicalize("register_user", &g).unwrap() {
        CanonicalizeResult::Matched { node, .. } => {
            assert_eq!(label_for(&g, node), "create user");
        }
        other => panic!("register_user should match create user, got {other:?}"),
    }
    assert!(matches!(
        canonicalize("register user", &g).unwrap(),
        CanonicalizeResult::Unmatched { .. }
    ));

    // 7. Daemon-earned state is NOT written by the write path: freshly derived
    //    concepts start at gc_survived = 0 / status None — P4/P6 earn it.
    for c in oracle
        .concepts
        .iter()
        .filter(|c| c.gc_survived > 0 || c.canonization_status != CanonizationStatus::None)
    {
        let node = by_content[&c.content];
        if let Node::Concept(built) = g.node(node).unwrap() {
            assert_eq!(built.gc_survived, 0, "gc_survived of {:?}", c.content);
            assert_eq!(
                built.canonization_status,
                CanonizationStatus::None,
                "status of {:?}",
                c.content
            );
        }
    }

    // 8. The demo fixture's hero concept is present and structurally wired:
    //    user schema has six aged inbound Dependency supporters and eight
    //    exclusive dependents — the Stage-2/3 canonization evidence (P6).
    let us = by_content["user schema"];
    let supporters: BTreeSet<String> = g
        .in_neighbors_typed(us, EdgeType::Dependency)
        .into_iter()
        .map(|id| label_for(&g, id))
        .collect();
    assert_eq!(
        supporters,
        BTreeSet::from([
            "create user".into(),
            "auth middleware".into(),
            "validation rules".into(),
            "password reset".into(),
            "rate limiter".into(),
            "error responses".into(),
        ])
    );
    let dependents: BTreeSet<String> = g
        .out_neighbors_typed(us, EdgeType::Dependency)
        .into_iter()
        .map(|id| label_for(&g, id))
        .collect();
    assert_eq!(
        dependents.len(),
        8,
        "user schema dependents: {dependents:?}"
    );

    // 9. ConceptType round-trips through the rebuild.
    assert!(g.concepts().all(|c| c.concept_type == ConceptType::Entity));
}
